import XCTest
@testable import BadwaterCore

/// Golden tests for the IMET .xlsx export layer: CRC-32, the STORE zip container,
/// the pure Wind/GeoPoint/mapping renderers, an end-to-end reproduction of the
/// real template's first data row, backward-compatible Codable, and the NWS spot
/// block. The generated bytes were validated to open in a real reader (openpyxl)
/// during development; these assertions lock the behavior on Linux CI.
final class ExportTests: XCTestCase {

    private func denver() -> Calendar {
        var c = Calendar(identifier: .gregorian)
        c.timeZone = TimeZone(identifier: "America/Denver")!
        return c
    }

    // MARK: - CRC-32

    func testCRC32Vectors() {
        func crc(_ s: String) -> UInt32 { CRC32.checksum(Array(s.utf8)) }
        XCTAssertEqual(crc(""), 0x0000_0000)
        XCTAssertEqual(crc("a"), 0xE8B7_BE43)
        XCTAssertEqual(crc("abc"), 0x3524_41C2)
        XCTAssertEqual(crc("123456789"), 0xCBF4_3926)
        XCTAssertEqual(crc("Div W - 7626"), 0x9FF2_F75C)
        XCTAssertEqual(CRC32.table[1], 0x7707_3096)
        XCTAssertEqual(CRC32.table[255], 0x2D02_EF8D)
    }

    // MARK: - ZIP container (byte-exact)

    func testZipByteExactFixture() {
        let out = ZipArchive.zip([("a.txt", Data("123456789".utf8))])
        let expected = Self.hex(
            "504b0304140000000000000021002639f4cb090000000900000005000000612e74787431323334" +
            "3536373839504b01021400140000000000000021002639f4cb09000000090000000500000000000000" +
            "00000000000000000000612e747874504b05060000000001000100330000002c0000000000")
        XCTAssertEqual(out, expected)
    }
    static func hex(_ s: String) -> Data {
        var d = Data(); var i = s.startIndex
        while i < s.endIndex { let j = s.index(i, offsetBy: 2); d.append(UInt8(s[i..<j], radix: 16)!); i = j }
        return d
    }

    // MARK: - Pure render types

    func testWindRenderings() {
        let w = Wind.measured(.init(low: 3, high: 5), .north, gust: 12)
        XCTAssertEqual(w.imetCell, "3-5 North, Gust 12")
        XCTAssertEqual(w.spotString, "N 3-5 Gust 12")
        XCTAssertEqual(Wind.lightVariable().imetCell, "Light/Variable")
        XCTAssertEqual(Wind.lightVariable().spotString, "Calm")
        XCTAssertEqual(Wind.measured(.init(low: 1, high: 5), .south).imetCell, "1-5 South")
        XCTAssertEqual(Wind.measured(.init(8), .southwest).imetCell, "8 Southwest")
        XCTAssertEqual(Wind.lightVariable(gust: 12).imetCell, "Light/Variable, Gust 12")
    }

    func testGeoPointRender() {
        XCTAssertEqual(GeoPoint(latitude: 38.21437, longitude: -112.3978).rendered, "38.21437, -112.3978")
        XCTAssertEqual(GeoPoint(latitude: 38.0, longitude: -112.0).rendered, "38, -112")
        XCTAssertEqual(GeoPoint(latitude: 38.2077, longitude: -112.41131).rendered, "38.2077, -112.41131")
    }

    func testTimeSerialAndSheetNaming() {
        let cal = denver()
        let nine = cal.date(from: DateComponents(year: 2026, month: 7, day: 6, hour: 9))!
        XCTAssertEqual(IMETExport.timeSerial(of: nine, calendar: cal), 0.375, accuracy: 1e-12)
        let one = cal.date(from: DateComponents(year: 2026, month: 7, day: 6, hour: 13))!
        XCTAssertEqual(IMETExport.timeSerial(of: one, calendar: cal), 0.5416666666666666, accuracy: 1e-12)
        let c = cal.dateComponents([.month, .day, .year], from: nine)
        XCTAssertEqual(IMETExport.sheetName(division: "Division W", c), "Div W - 7626")
        XCTAssertEqual(IMETExport.titleLine(division: "Division W", location: "659 Road", c),
                       "7/6/26 Weather Observations - Division W, 659 Road")
        let ten = cal.dateComponents([.month, .day, .year],
                                     from: cal.date(from: DateComponents(year: 2026, month: 7, day: 10, hour: 9))!)
        XCTAssertEqual(IMETExport.sheetName(division: "Division W", ten), "Div W - 71026")
    }

    // MARK: - End-to-end workbook (search the uncompressed STORE bytes)

    func testWorkbookReproducesSampleRowAndBlankRules() {
        let cal = denver()
        let ts = cal.date(from: DateComponents(year: 2026, month: 7, day: 6, hour: 9))!
        let slung = obs(cal: cal, ts: ts, dry: 55, depression: 7, rh: 47,
                        wind: .measured(.init(low: 1, high: 3), .south), elev: 10700,
                        loc: GeoPoint(latitude: 38.21437, longitude: -112.3978))
        let data = IMETWorkbook.build(from: Shift(started: ts, obs: [slung],
                                                  division: "Division W", locationName: "659 Road"),
                                      calendar: cal)
        func has(_ s: String) -> Bool { data.range(of: Data(s.utf8)) != nil }
        XCTAssertEqual(Array(data.prefix(2)), [0x50, 0x4B])   // "PK" zip signature
        XCTAssertTrue(has("7/6/26 Weather Observations - Division W, 659 Road"))
        XCTAssertTrue(has("Probability of Ignition (Unshaded) (%)"))
        XCTAssertTrue(has("<c r=\"A3\" s=\"1\"><v>0.375</v></c>"))
        XCTAssertTrue(has("<c r=\"B3\"><v>55</v></c>"))
        XCTAssertTrue(has("<c r=\"C3\"><v>48</v></c>"))       // wet = dry 55 − depression 7
        XCTAssertTrue(has("1-3 South"))
        XCTAssertTrue(has("<v>10700</v>"))
        XCTAssertTrue(has("38.21437, -112.3978"))

        // A Kestrel obs (not slung, no wind/elev/location) omits those cells entirely.
        let d2 = IMETWorkbook.build(from: Shift(started: ts, obs: [
            obs(cal: cal, ts: ts, dry: 60, depression: nil, rh: 30, wind: nil, elev: nil, loc: nil)
        ]), calendar: cal)
        XCTAssertNil(d2.range(of: Data("r=\"C3\"".utf8)))     // no wet bulb cell
        XCTAssertNil(d2.range(of: Data("r=\"E3\"".utf8)))     // no wind cell
        XCTAssertNil(d2.range(of: Data("r=\"J3\"".utf8)))     // no location cell
    }

    func testMultiDayGrouping() {
        let cal = denver()
        let d1 = cal.date(from: DateComponents(year: 2026, month: 7, day: 6, hour: 23, minute: 30))!
        let d2 = cal.date(from: DateComponents(year: 2026, month: 7, day: 7, hour: 0, minute: 30))!
        let sheets = IMETExport.sheets(from: Shift(started: d1, obs: [
            obs(cal: cal, ts: d1, dry: 60, depression: nil, rh: 30, wind: nil, elev: nil, loc: nil),
            obs(cal: cal, ts: d2, dry: 58, depression: nil, rh: 35, wind: nil, elev: nil, loc: nil),
        ], division: "Division W"), calendar: cal)
        XCTAssertEqual(sheets.map(\.name), ["Div W - 7626", "Div W - 7726"])
        XCTAssertEqual(sheets.map { $0.rows.count }, [1, 1])
    }

    // MARK: - Backward-compatible Codable

    func testCodableOmitsNilNewFields() throws {
        let o = obs(cal: .current, ts: Date(timeIntervalSince1970: 0), dry: 70, depression: nil, rh: 20, wind: nil, elev: nil, loc: nil)
        let json = String(data: try JSONEncoder().encode(o), encoding: .utf8)!
        // nil optionals are omitted -> byte-identical to pre-feature JSON, which thus decodes.
        XCTAssertFalse(json.contains("\"wind\""))
        XCTAssertFalse(json.contains("elevationFeet"))
        XCTAssertFalse(json.contains("\"location\""))
        let back = try JSONDecoder().decode(WeatherObs.self, from: Data(json.utf8))
        XCTAssertNil(back.wind); XCTAssertNil(back.elevationFeet); XCTAssertNil(back.location)
        let sh = Shift(started: Date(timeIntervalSince1970: 0), obs: [o])
        XCTAssertFalse(String(data: try JSONEncoder().encode(sh), encoding: .utf8)!.contains("division"))
    }

    // MARK: - Spot block

    func testSpotObservationsBlock() {
        let header = SpotObsHeader(site: "Division W 659 Road", latLong: "38.21437, -112.3978",
                                   elevationFeet: 10700, aspect: "West", dateLabel: "7/6/26")
        let rows = [
            SpotObsLine(timeHHmm: "0900", dryBulbF: 55, wetBulbF: 48, relativeHumidity: 47, dewPointF: 36, windText: "S 1-3", poiUnshaded: 30, poiShaded: 20, monthDay: "7/6"),
            SpotObsLine(timeHHmm: "0030", dryBulbF: 51, wetBulbF: nil, relativeHumidity: 58, dewPointF: nil, windText: "Calm", poiUnshaded: 20, poiShaded: 10, monthDay: "7/7"),
        ]
        let out = SpotObservationsRenderer.plainText(header: header, rows: rows, includePoI: true)
        XCTAssertTrue(out.hasPrefix("On-site weather observations - Division W 659 Road\n"))
        XCTAssertTrue(out.contains("PoI(U/S)"))
        XCTAssertTrue(out.contains("-- 7/7 --"))            // divider at local-midnight rollover
        XCTAssertTrue(out.contains("not observed, not a forecast"))
        XCTAssertTrue(out.hasSuffix("not affiliated with NWS/NWCG.\n"))
        XCTAssertTrue(out.unicodeScalars.allSatisfy { $0.isASCII })
        for line in out.split(separator: "\n", omittingEmptySubsequences: false) {
            XCTAssertFalse(line.hasSuffix(" "), "trailing space in: \(line)")
        }
        XCTAssertFalse(SpotObservationsRenderer.plainText(header: header, rows: rows, includePoI: false).contains("PoI(U/S)"))
    }

    // MARK: - helper

    private func obs(cal: Calendar, ts: Date, dry: Int, depression: Int?, rh: Int, wind: Wind?, elev: Int?, loc: GeoPoint?, aspect: Aspect = .west) -> WeatherObs {
        let input = IgnitionInput(
            dryBulbF: dry, relativeHumidity: rh, month: cal.component(.month, from: ts),
            timeOfDay: TimeOfDay.from(hour: cal.component(.hour, from: ts)),
            aspect: aspect, slope: .gentle, elevationDelta: .level)
        let humidity = depression.map {
            HumidityResult(relativeHumidity: rh, dewPointF: 36, wetBulbDepressionF: $0, elevationBand: .band3)
        }
        return WeatherObs(
            timestamp: ts, estimate: IgnitionCalculator.estimate(input),
            humidity: humidity, rhSource: depression != nil ? .wetBulb : .direct,
            wind: wind, elevationFeet: elev, location: loc)
    }
}
