// Cross-implementation conformance harness: replays the golden vectors emitted
// from BadwaterCore (vectors.json, regenerated by `swift run badwater-vectors`)
// against the web engine (web/engine.js). Zero dependencies — run with:
//
//   node conformance/check-web.js
//
// A failure here means the Swift core and the web port disagree. Fix the side
// that is wrong (the Swift core is the source of truth; vectors.json is checked
// for staleness against it in CI, so a red run here almost always means
// web/engine.js needs the port). See docs/PARITY.md.

// xlsx sheet names/titles derive from dates; pin the zone BEFORE any Date use
// so both generators agree. (CI also sets TZ=UTC at the job level.)
process.env.TZ = "UTC";

const assert = require("node:assert");
const path = require("node:path");

const E = require(path.join(__dirname, "..", "web", "engine.js"));
const V = require(path.join(__dirname, "vectors.json"));

let checks = 0;
const failures = [];
function eq(actual, expected, label) {
  checks++;
  try {
    assert.deepStrictEqual(actual, expected);
  } catch {
    failures.push(`${label}\n    expected: ${JSON.stringify(expected)}\n    actual:   ${JSON.stringify(actual)}`);
  }
}

//---------------- Table data (transcription drift is the #1 real risk) ----------------
eq(E.REF_GRID, V.tables.refGrid, "Table A grid (REF_GRID)");
for (const g of ["B", "C", "D"]) {
  eq(E.CORR[g].u, V.tables.corr[g].u, `Table ${g} unshaded grid (CORR.${g}.u)`);
  eq(E.CORR[g].s, V.tables.corr[g].s, `Table ${g} shaded grid (CORR.${g}.s)`);
}
eq(E.PIG_U, V.tables.pigU, "PIG unshaded grid (PIG_U)");
eq(E.PIG_S, V.tables.pigS, "PIG shaded grid (PIG_S)");

//---------------- Lookup / banding math ----------------
for (const [t, rh, x] of V.rfmCases) eq(E.referenceFM(t, rh), x, `referenceFM(${t}, ${rh})`);
for (const [g, sh, a, sl, b, d, x] of V.corrCases)
  eq(E.correction(g, sh === "s", a, sl === "steep", b, d), x, `correction(${g}, ${sh}, ${a}, ${sl}, band ${b}, ${d})`);
for (const [t, f, sh, x] of V.pigCases) eq(E.pig(t, f, sh === "s"), x, `pig(${t}, ffm ${f}, ${sh})`);

//---------------- Fire-behavior interpretation ----------------
eq(E.BEHAV, V.behaviorTable, "fire-behavior table (BEHAV titles/ranges/details)");
eq(E.CAUTION, V.caution, "IRPG caution note");
for (const [p, idx] of V.behaviorCases) eq(E.behavior(p), idx, `behavior(${p})`);

//---------------- Calendar / clock banding ----------------
for (const [m, g] of V.monthGroupCases) eq(E.monthGroup(m), g, `monthGroup(${m})`);
for (const [h, m, band] of V.timeBandCases) {
  const want = band === "night" ? "night" : parseInt(band, 10);
  eq(E.timeBandFromClock(h, m), want, `timeBandFromClock(${h}, ${m})`);
}

//---------------- Psychrometrics + elevation bands ----------------
for (const [dry, wet, band, rh, dew, dep] of V.psychroCases)
  eq(E.psychro(dry, wet, E.bandByNum(band).p), { rh, dew, dep }, `psychro(${dry}, ${wet}, band ${band})`);
for (const [feet, ak, band] of V.elevationBandCases)
  eq(E.bandForElev(feet, !!ak), band, `bandForElev(${feet}, alaska=${!!ak})`);

//---------------- Full ignition chain ----------------
for (const c of V.chainCases) {
  const [dryBulbF, rh, month, tb, aspect, slope, delta, rf, night, corrU, corrS, ffmU, ffmS, pigU, pigS, behU, behS] = c;
  const timeBand = tb === "night" ? "night" : parseInt(tb, 10);
  const e = E.estimate({ dryBulbF, rh, month, timeBand, aspect, slope, elevationDelta: delta });
  eq(
    { rf: e.rf, night: e.night, corrU: e.unshaded.corr, corrS: e.shaded.corr,
      ffmU: e.unshaded.ffm, ffmS: e.shaded.ffm, pigU: e.unshaded.pig, pigS: e.shaded.pig,
      behU: e.unshaded.b, behS: e.shaded.b },
    { rf, night, corrU, corrS, ffmU, ffmS, pigU, pigS, behU, behS },
    `estimate(${dryBulbF}°F, RH ${rh}, month ${month}, band ${tb}, ${aspect}/${slope}/${delta})`
  );
}

//---------------- Wind renderings ----------------
for (const [low, high, dir, gust, spot, spoken, imet] of V.windCases) {
  const w = { low, high, dir, gust };
  eq(E.windSpot(w), spot, `windSpot(${JSON.stringify(w)})`);
  eq(E.windSpoken(w), spoken, `windSpoken(${JSON.stringify(w)})`);
  eq(E.windImet(w), imet, `windImet(${JSON.stringify(w)})`);
}

//---------------- CRC32 ----------------
for (const [text, crc] of V.crc32Cases)
  eq(E.crc32(new TextEncoder().encode(text)), crc, `crc32(${JSON.stringify(text)})`);

//---------------- Radio script ----------------
for (const c of V.radioCases)
  eq(E.broadcastScript(c.addressee, c.cur, c.prev), c.expect, `radio script: ${c.name}`);

//---------------- IMET .xlsx (byte-exact) ----------------
if (new Date().getTimezoneOffset() !== 0) {
  failures.push("xlsx cases skipped: process is not running in UTC (set TZ=UTC) — date-derived sheet names would differ");
} else {
  for (const c of V.xlsxCases) {
    checks++;
    const want = Buffer.from(c.b64, "base64");
    const got = Buffer.from(E.buildXlsx(c.shifts, c.coordLat, c.coordLon));
    if (!want.equals(got)) {
      let off = 0;
      const n = Math.min(want.length, got.length);
      while (off < n && want[off] === got[off]) off++;
      const ctx = (buf) => JSON.stringify(buf.slice(Math.max(0, off - 24), off + 40).toString("latin1"));
      failures.push(
        `xlsx bytes: ${c.name} — lengths ${want.length}/${got.length}, first diff at offset ${off}\n` +
        `    expected …${ctx(want)}…\n    actual   …${ctx(got)}…`
      );
    }
  }
}

//---------------- Known divergence (documented, not yet asserted) ----------------
// web/app.js edge() approximates BadwaterCore's SensitivityAnalysis (4-corner
// probe, ±3 °F wet bulb vs the core's 3×3 grid, ±2 °F). vectors.json already
// carries `sensitivityCases`; when the full port lands in engine.js, assert
// them here. Tracked in docs/PARITY.md — do not delete this notice silently.
const skippedSensitivity = V.sensitivityCases.length;

//---------------- Report ----------------
const MAX_SHOWN = 20;
if (failures.length) {
  console.error(`\nCONFORMANCE FAILED — web/engine.js disagrees with BadwaterCore on ${failures.length} of ${checks} checks:\n`);
  for (const f of failures.slice(0, MAX_SHOWN)) console.error("  ✗ " + f + "\n");
  if (failures.length > MAX_SHOWN) console.error(`  … and ${failures.length - MAX_SHOWN} more`);
  console.error("Source of truth is Sources/BadwaterCore — port the change to web/engine.js (see docs/PARITY.md).");
  process.exit(1);
}
console.log(`conformance OK — ${checks} checks against BadwaterCore vectors, 0 mismatches` +
  (skippedSensitivity ? ` (${skippedSensitivity} sensitivity cases skipped: known divergence, see docs/PARITY.md)` : ""));
