import SwiftUI
import PlateworksCore

/// Semantic color tokens for Plateworks Ignition, backed by the asset catalog
/// (`Assets.xcassets/Colors`, generated by `scripts/generate_color_assets.py`).
///
/// Design intent — the Badwater Basin identity:
/// - **Pool teal** is the sole brand accent (the teal spring against white salt).
/// - The **warm ramp is reserved for fire-behavior severity** — orange on screen
///   always means danger, never decoration.
/// - Two grounds: salt-flat (light) and basin-night (dark, near-black to protect
///   dark adaptation on the line).
enum PlateworksColor {
    static let background = Color("BasinBackground")
    static let surface = Color("Surface")
    static let surfaceRaised = Color("SurfaceRaised")
    static let surfaceSunk = Color("SurfaceSunk")

    static let ink = Color("Ink")
    static let muted = Color("Muted")
    static let hairline = Color("Hairline")

    static let accent = Color("PoolTeal")
    static let accentSunk = Color("PoolTealSunk")
    static let caution = Color("SignalAmber")

    /// The fire-behavior severity color for a computed interpretation.
    static func severity(_ behavior: FireBehavior) -> Color {
        switch behavior {
        case .veryLow: return Color("SeverityVeryLow")
        case .low: return Color("SeverityLow")
        case .medium: return Color("SeverityMedium")
        case .high: return Color("SeverityHigh")
        case .veryHigh: return Color("SeverityVeryHigh")
        case .extreme: return Color("SeverityExtreme")
        }
    }
}

extension FireBehavior {
    /// Convenience accessor for the severity color of this interpretation.
    var color: Color { PlateworksColor.severity(self) }
}
